name: 'Install DBSnapper Agent'
description: 'Install the DBSnapper Agent in a GitHub Actions workflow'
author: 'DBSnapper'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'database'
  color: 'blue'

# Define your inputs here.
inputs:
  version:
    description: 'Version of the DBSnapper Agent to install'
    required: false
    default: latest

runs:
  using: node20
  main: dist/index.js
